// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"LogoTitleScreen","status":true,"description":"Menampilkan logo UNIKU & DGMC kecil di pojok kanan atas, sejajar horizontal - by ChatGPT","parameters":{}}
];
